INSERT INTO public.types (description, code) VALUES ('Tipo Vivienda - departamento ', 'HS2');
INSERT INTO public.types (description, code) VALUES ('Tipo Vivienda - Covacha', 'HS6');
INSERT INTO public.types (description, code) VALUES ('Tipo de via - Carretera', 'RD3');
INSERT INTO public.types (description, code) VALUES ('Tipo Vivienda - vivienda colectiva', 'HS18');
INSERT INTO public.types (description, code) VALUES ('Ocupacion colectiva sin residentes habituales', 'OPc2');
INSERT INTO public.types (description, code) VALUES ('Tipo Vivienda - Casa o villa', 'HS1');
INSERT INTO public.types (description, code) VALUES ('Ocupacion particular de temporada o vacacional', 'OPp3');
INSERT INTO public.types (description, code) VALUES ('Tipo de via - Otro', 'RD8');
INSERT INTO public.types (description, code) VALUES ('Tipo de via - Camino', 'RD7');
INSERT INTO public.types (description, code) VALUES ('Tipo Vivienda - Asilo / residencia adultos mayores', 'HS15');
INSERT INTO public.types (description, code) VALUES ('Tipo Vivienda - Campamento de trabajo', 'HS17');
INSERT INTO public.types (description, code) VALUES ('Ocupacion particular en construccion', 'OPp5');
INSERT INTO public.types (description, code) VALUES ('Tipo Vivienda - Hospital / clinica', 'HS12');
INSERT INTO public.types (description, code) VALUES ('Tipo Vivienda - choza', 'HS7');
INSERT INTO public.types (description, code) VALUES ('Ocupacion particular con personas presentes', 'OPp1');
INSERT INTO public.types (description, code) VALUES ('Tipo Vivienda - carcel', 'HS11');
INSERT INTO public.types (description, code) VALUES ('Tipo de via - Calle', 'RD1');
INSERT INTO public.types (description, code) VALUES ('Tipo Vivienda - cuartel militar / policia / bomberos', 'HS10');
INSERT INTO public.types (description, code) VALUES ('Ocupacion colectiva Ocupacion particular con personas presentes residentes habituales', 'OPc1');
INSERT INTO public.types (description, code) VALUES ('Ocupacion particular desocupada', 'OPp4');
INSERT INTO public.types (description, code) VALUES ('Tipo Vivienda - media agua', 'HS4');
INSERT INTO public.types (description, code) VALUES ('Tipo de via - Pasaje', 'RD4');
INSERT INTO public.types (description, code) VALUES ('Tipo Vivienda - centro de acogida para ninos / adolc', 'HS14');
INSERT INTO public.types (description, code) VALUES ('Tipo Vivienda - Cuarto / casa de inquilinato', 'HS3');
INSERT INTO public.types (description, code) VALUES ('Tipo de via - Sendero', 'RD6');
INSERT INTO public.types (description, code) VALUES ('Tipo Vivienda - Convento ', 'HS13');
INSERT INTO public.types (description, code) VALUES ('Tipo Vivienda - Internado estudiantes', 'HS16');
INSERT INTO public.types (description, code) VALUES ('Ocupacion particular con personas ausentes', 'OPp2');
INSERT INTO public.types (description, code) VALUES ('Tipo Vivienda - Sin vivienda', 'HS19');
INSERT INTO public.types (description, code) VALUES ('Tipo de via - Callejon', 'RD5');
INSERT INTO public.types (description, code) VALUES ('Tipo Vivienda - rancho', 'HS5');
INSERT INTO public.types (description, code) VALUES ('Tipo de via - Avenida', 'RD2');
INSERT INTO public.types (description, code) VALUES ('Tipo Vivienda - Otra vivienda particular', 'HS8');
INSERT INTO public.types (description, code) VALUES ('Tipo Vivienda - Hotel, hostal, residencial, pension', 'HS9');
INSERT INTO public.types (description, code) VALUES ('Por tuberia, fuera del edificio, lote o terreno', 'WS3');
INSERT INTO public.types (description, code) VALUES ('Fuente agua - Carro o tanquero repartidor', 'WSC4');
INSERT INTO public.types (description, code) VALUES ('Servicio Higienico - Inodoro o escusado con descarga directa al mar', 'ST5');
INSERT INTO public.types (description, code) VALUES ('Fuente agua - Pozo', 'WSC3');
INSERT INTO public.types (description, code) VALUES ('No recibe agua por tuberia, sino por otros medios', 'WS4');
INSERT INTO public.types (description, code) VALUES ('Por tuberia fuera de vivienda pero dentro del edificio', 'WS2');
INSERT INTO public.types (description, code) VALUES ('Servicio Higienico - Letrina', 'ST6');
INSERT INTO public.types (description, code) VALUES ('Servicio Higienico - Inodoro o escusado con conexion a alcanterillado', 'ST1');
INSERT INTO public.types (description, code) VALUES ('Fuente agua - Otras fuentes', 'WSC5');
INSERT INTO public.types (description, code) VALUES ('Servicio Higienico - No tiene', 'ST7');
INSERT INTO public.types (description, code) VALUES ('Fuente agua - Empresa publica / municipio', 'WSC1');
INSERT INTO public.types (description, code) VALUES ('Servicio Higienico - Inodoro o escusado con conexion a pozo ciego', 'ST4');
INSERT INTO public.types (description, code) VALUES ('Fuente agua - Junta de agua', 'WSC2');
INSERT INTO public.types (description, code) VALUES ('Por tuberia dentro de la vivienda', 'WS1');
INSERT INTO public.types (description, code) VALUES ('Servicio Higienico - Inodoro o escusado con conexion a biodigestor', 'ST3');
INSERT INTO public.types (description, code) VALUES ('Servicio Higienico - Inodoro o escusado con conexion a pozo septico', 'ST2');
INSERT INTO public.types (description, code) VALUES ('Electricidad - no dispone', 'ES5');
INSERT INTO public.types (description, code) VALUES ('Basura - Por carro recolector', 'WD1');
INSERT INTO public.types (description, code) VALUES ('Basura - La entierra', 'WD5');
INSERT INTO public.types (description, code) VALUES ('Electricidad - energia solar', 'ES2');
INSERT INTO public.types (description, code) VALUES ('Basura - De otra forma', 'WD7');
INSERT INTO public.types (description, code) VALUES ('Electricidad - Planta electrica', 'ES1');
INSERT INTO public.types (description, code) VALUES ('Electricidad - Otra Fuente', 'ES4');
INSERT INTO public.types (description, code) VALUES ('Basura - La quema', 'WD4');
INSERT INTO public.types (description, code) VALUES ('Basura - La arroja a fuente agua', 'WD6');
INSERT INTO public.types (description, code) VALUES ('Electricidad - energia eolica', 'ES3');
INSERT INTO public.types (description, code) VALUES ('Basura - Por contenedor municipal', 'WD2');
INSERT INTO public.types (description, code) VALUES ('Basura - La arroja en terreno baldio', 'WD3');



INSERT INTO public.conditions (description, code) VALUES ('Bueno', 1);
INSERT INTO public.conditions (description, code) VALUES ('regular', 2);
INSERT INTO public.conditions (description, code) VALUES ('malo', 3);

INSERT INTO public.cantons (canton_id, name) VALUES (904, 'BALZAR');
INSERT INTO public.cantons (canton_id, name) VALUES (909, 'EL TRIUNFO');
INSERT INTO public.cantons (canton_id, name) VALUES (905, 'COLIMES');
INSERT INTO public.cantons (canton_id, name) VALUES (903, 'BALAO');
INSERT INTO public.cantons (canton_id, name) VALUES (902, 'ALFREDO BAQUERIZO MORENO (JUJAN)');
INSERT INTO public.cantons (canton_id, name) VALUES (907, 'DURAN');
INSERT INTO public.cantons (canton_id, name) VALUES (901, 'GUAYAQUIL');
INSERT INTO public.cantons (canton_id, name) VALUES (908, 'EL EMPALME');
INSERT INTO public.cantons (canton_id, name) VALUES (906, 'DAULE');
INSERT INTO public.cantons (canton_id, name) VALUES (910, 'MILAGRO');
INSERT INTO public.cantons (canton_id, name) VALUES (921, 'PLAYAS');
INSERT INTO public.cantons (canton_id, name) VALUES (911, 'NARANJAL');
INSERT INTO public.cantons (canton_id, name) VALUES (913, 'PALESTINA');
INSERT INTO public.cantons (canton_id, name) VALUES (925, 'NOBOL');
INSERT INTO public.cantons (canton_id, name) VALUES (914, 'PEDRO CARBO');
INSERT INTO public.cantons (canton_id, name) VALUES (924, 'LOMAS DE SARGENTILLO');
INSERT INTO public.cantons (canton_id, name) VALUES (928, 'ISIDRO AYORA');
INSERT INTO public.cantons (canton_id, name) VALUES (923, 'CORONEL MARCELINO MARIDUENA');
INSERT INTO public.cantons (canton_id, name) VALUES (927, 'GENNERAL ANTONIO ELIZALDE');
INSERT INTO public.cantons (canton_id, name) VALUES (918, 'SANTA LUCIA');
INSERT INTO public.cantons (canton_id, name) VALUES (916, 'SAMBORONDON');
INSERT INTO public.cantons (canton_id, name) VALUES (919, 'SALITRE');
INSERT INTO public.cantons (canton_id, name) VALUES (920, 'SAN JACINTO DE YAGUACHI');
INSERT INTO public.cantons (canton_id, name) VALUES (912, 'NARANJITO');
INSERT INTO public.cantons (canton_id, name) VALUES (922, 'SIMON BOLIVAR');

INSERT INTO public.materials (description, code) VALUES ('Pared - Panel prefabricado', 'WL3');
INSERT INTO public.materials (description, code) VALUES ('Techo - Zinc aluminio', 'RF3');
INSERT INTO public.materials (description, code) VALUES ('Techo - Otro material', 'RF6');
INSERT INTO public.materials (description, code) VALUES ('Pared - Hormigon', 'WL1');
INSERT INTO public.materials (description, code) VALUES ('Piso - tabla sin tratar', 'FL5');
INSERT INTO public.materials (description, code) VALUES ('Piso - marmol o marmeton', 'FL3');
INSERT INTO public.materials (description, code) VALUES ('Piso - Ceramica baldoso, vinil o porcelanato', 'FL2');
INSERT INTO public.materials (description, code) VALUES ('Pared - Adobe o tapia', 'WL4');
INSERT INTO public.materials (description, code) VALUES ('Techo - Hormigon', 'RF1');
INSERT INTO public.materials (description, code) VALUES ('Pared - Otro material', 'WL8');
INSERT INTO public.materials (description, code) VALUES ('Piso - Tierra', 'FL7');
INSERT INTO public.materials (description, code) VALUES ('Techo - teja', 'RF4');
INSERT INTO public.materials (description, code) VALUES ('Piso - Otro material', 'FL8');
INSERT INTO public.materials (description, code) VALUES ('Pared - Cana no revestida', 'WL7');
INSERT INTO public.materials (description, code) VALUES ('Pared - Madera', 'WL5');
INSERT INTO public.materials (description, code) VALUES ('Techo - fibrocemento', 'RF2');
INSERT INTO public.materials (description, code) VALUES ('Pared - Cana revestida', 'WL6');
INSERT INTO public.materials (description, code) VALUES ('Piso - duela, parquet, tablo o piso flotante', 'FL1');
INSERT INTO public.materials (description, code) VALUES ('Techo - Palma u Hoja', 'RF5');
INSERT INTO public.materials (description, code) VALUES ('Piso - cana sin tratar', 'FL6');
INSERT INTO public.materials (description, code) VALUES ('Piso - Ladrillo o cemento', 'FL4');
INSERT INTO public.materials (description, code) VALUES ('Pared - Ladrillo o bloque', 'WL2');


